site_name: Tianocore Edk2 Pytool Extensions (edk2toolext)
repo_url: https://github.com/tianocore/edk2-pytool-extensions
copyright: Copyright (c) Microsoft.  All rights reserved
site_description: edk2toolext package documentation

theme:
  name: readthedocs

docs_dir: docs/user

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
  - exclude:
      glob:
        - coverage.md
        - publishing.md
        - developing.md
  - gen-files:
      scripts:
        - docs/user/gen_api.py
  - awesome-pages

extra_javascript:
  - https://unpkg.com/mermaid@8.7.0/dist/mermaid.min.js

markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition
  - codehilite
  - meta
  - fenced_code
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed
  - toc:
      permalink: true
watch:
  - 'docs/user'
  - 'mkdocs.yml'
  - 'edk2toolext/'

nav:
  - Our Philosophy: index.md
  - Using Stuart:
    - Installation Instructions: using/install.md
    - Build Instructions: using/build.md
    - Core CI Instructions: using/ci.md
  - Integrating Stuart:
    - Build with Stuart: integrate/build.md
    - Core CI with Stuart: integrate/manage.md
    - Porting Example: integrate/porting.md
  - ... | tools/**/*.md
  - Advanced Features:
    - Invocables: features/invocable.md
    - Creating Invocables: features/creating_invocable.md
    - Ext Deps: features/extdep.md
    - Creating Ext Deps: features/creating_extdep.md
    - Plugins: features/plugin_manager.md
    - Create a Plugin: features/creating_plugins.md
    - Environment Variables: features/environment_variables.md
    - Self Describing Environment: features/sde.md
    - Settings Manager: features/settings_manager.md
    - Logging: features/logging.md
    - WSL: features/using_linux.md
  - API Reference:
    - ... | flat | api/**/*.md
