##
# Azure Pipeline build file for a releasing to pypi

# Copyright (c) 2019, Microsoft Corporation
# SPDX-License-Identifier: BSD-2-Clause-Patent
##

# trigger on master for CI and all PRs for master
trigger: 
- master

pr: 
- master

jobs:
- template: templates/build-test-job.yml
  parameters:
    vm_image: 'windows-latest'
    root_package_folder: "edk2toolext"

- template: templates/build-test-job.yml
  parameters:
    vm_image: 'ubuntu-latest'
    root_package_folder: "edk2toolext"
